info:
  namespace: valhallafix
items:
  button_return_to_menu:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: BOOK
      generate: true
      model_id: 1829130
      textures:
      - item/gui/button_return_to_menu