info:
  namespace: valhallafix
items:
  royal_diamond_helmet:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: DIAMOND_HELMET
      generate: true
      model_id: 9918292
      textures:
      - item/armor/royal_diamond_helmet