info:
  namespace: valhallafix
items:
  royal_diamond_axe:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: DIAMOND_AXE
      model_id: 1981900
      generate: false
      model_path: item/tools/royal_diamond_axe