info:
  namespace: valhallafix
items:
  button_custom_tool_requirement:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: DIAMOND_PICKAXE
      model_id: 1829130
      generate: false
      model_path: item/gui/button_custom_tool_requirement
  royal_diamond_pickaxe:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: DIAMOND_PICKAXE
      model_id: 1981900
      generate: false
      model_path: item/tools/royal_diamond_pickaxe