info:
  namespace: valhallafix
items:
  copper_shovel:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: IRON_SHOVEL
      model_id: 9918290
      generate: false
      model_path: item/tools/copper_shovel
  skillicon_iron_shovel_fix:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: IRON_SHOVEL
      model_id: 3510002
      generate: false
      model_path: item/gui/skillicon_iron_shovel_fix