info:
  namespace: valhallafix
items:
  button_select_tool:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: IRON_HOE
      model_id: 1829130
      generate: false
      model_path: item/gui/button_select_tool
  skillicon_farming:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: IRON_HOE
      model_id: 3510001
      generate: false
      model_path: item/gui/skillicon_farming
  copper_hoe:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: IRON_HOE
      model_id: 9918290
      generate: false
      model_path: item/tools/copper_hoe