info:
  namespace: valhallafix
items:
  hot_iron_ingot:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: IRON_INGOT
      generate: true
      model_id: 9827320
      textures:
      - item/materials/hot_iron_ingot