info:
  namespace: valhallafix
items:
  skillicon_mining:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: IRON_PICKAXE
      model_id: 3510001
      generate: false
      model_path: item/gui/skillicon_mining
  copper_pickaxe:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: IRON_PICKAXE
      model_id: 9918290
      generate: false
      model_path: item/tools/copper_pickaxe