info:
  namespace: valhallafix
items:
  skillicon_heavyweapons:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: IRON_AXE
      model_id: 3510001
      generate: false
      model_path: item/gui/skillicon_heavyweapons
  skillicon_landscaping:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: IRON_AXE
      model_id: 3510002
      generate: false
      model_path: item/gui/skillicon_landscaping
  copper_axe:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: IRON_AXE
      model_id: 9918290
      generate: false
      model_path: item/tools/copper_axe