info:
  namespace: valhallafix
items:
  assassin_leggings:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: LEATHER_LEGGINGS
      generate: true
      model_id: 9918291
      textures:
      - item/armor/assassin_leggings
  turtle_leggings:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: LEATHER_LEGGINGS
      generate: true
      model_id: 9918294
      textures:
      - item/armor/turtle_leggings