info:
  namespace: valhallafix
items:
  assassin_helmet:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: LEATHER_HELMET
      generate: true
      model_id: 9918291
      textures:
      - item/armor/assassin_helmet