info:
  namespace: valhallafix
items:
  royal_netherite_boots:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: NETHERITE_BOOTS
      generate: true
      model_id: 9918293
      textures:
      - item/armor/royal_netherite_boots