info:
  namespace: valhallafix
items:
  royal_netherite_pickaxe:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: NETHERITE_PICKAXE
      model_id: 1981900
      generate: false
      model_path: item/tools/royal_netherite_pickaxe