info:
  namespace: valhallafix
items:
  netherite_shears:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: SHEARS
      model_id: 8177280
      generate: false
      model_path: item/tools/netherite_shears
