info:
  namespace: valhallafix
items:
  button_save:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: STRUCTURE_VOID
      generate: true
      model_id: 1829130
      textures:
      - item/gui/button_save
  button_confirm_selection:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: STRUCTURE_VOID
      generate: true
      model_id: 1829131
      textures:
      - item/gui/button_confirm_selection