info:
  namespace: valhallafix
items:
  wooden_dagger:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: WOODEN_SWORD
      model_id: 1981820
      generate: false
      model_path: item/weapons/wooden_dagger
  wooden_mace:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: WOODEN_SWORD
      model_id: 1981821
      generate: false
      model_path: item/weapons/wooden_mace
  wooden_rapier:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: WOODEN_SWORD
      model_id: 1981822
      generate: false
      model_path: item/weapons/wooden_rapier
  wooden_warhammer:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: WOODEN_SWORD
      model_id: 1981825
      generate: false
      model_path: item/weapons/wooden_warhammer
  wooden_spear:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: WOODEN_SWORD
      model_id: 1981826
      generate: false
      model_path: item/weapons/wooden_spear
  wooden_greataxe:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: WOODEN_SWORD
      model_id: 1981827
      generate: false
      model_path: item/weapons/wooden_greataxe
  wooden_knuckles:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: WOODEN_SWORD
      model_id: 1981840
      generate: false
      model_path: item/weapons/wooden_knuckles