info:
  namespace: valhallafix
items:
  netherite_jewelry_hammer:
    display_name: valhallafix
    permission: valhallafix
    resource:
      material: WOODEN_PICKAXE
      model_id: 8877280
      generate: false
      model_path: item/tools/netherite_jewelry_hammer